path:
  ckpt_path: "./output/ckpt/VCTK"
  log_path: "./output/log/VCTK"
  result_path: "./output/result/VCTK"
optimizer:
  batch_size: 32
  betas: [0.5, 0.9]
  gamma: 0.999
  grad_clip_thresh: 1
  grad_acc_step: 1
  init_lr_G: 0.0001
  init_lr_D: 0.0002
optimizer_fs2:
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  warm_up_step: 2000
  anneal_steps: [60000, 120000, 180000]
  anneal_rate: 0.3
loss:
  adv_loss_mode: "lsgan"
  noise_loss: "l1"
  dur_loss: "mse"
  pitch_loss: "l1"
  cwt_loss: "l1"
  # cwt_add_f0_loss: false
  lambda_f0: 1.0
  lambda_uv: 1.0
  lambda_ph_dur: 1.0
  lambda_word_dur: 0.0 # lambda_word_dur should not be activated, otherwise it will produce NaN value (For VCTK)
  lambda_sent_dur: 1.0
  lambda_d: 0.1
  lambda_p: 0.1
  lambda_e: 0.1
  lambda_fm: 10.0
step:
  total_step: 300000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 20000
